### ISSUE TITLE
[Bug] README 文件中的数据地址错误

### ISSUE THREAD

**Issue by WencWu** [open-compass/CriticEval#1]
#### 1.1 Prepare Dataset

Download the dataset from [huggingface dataset](https://huggingface.co/datasets/opencompass/CriticBench) by running this command:
```bash
mkdir data
cd data
git clone https://huggingface.co/datasets/opencompass/CriticEval
```
其中的 https://huggingface.co/datasets/opencompass/CriticEval 在 huggingface 查不到，应改为

```bash
git clone https://huggingface.co/datasets/opencompass/CriticBench
```

**Comment by gmftbyGMFTBY** [comment]
Thanks for your reminder!
